### ISSUE TITLE
No sex?

### ISSUE THREAD

**Issue by skoove** [cinder-OwO/pong_TWO---11--1-#1]
I cannot believe that this game does not include the ability to have sex with any of the three characters (Ball, Paddle -1 and paddle 0) I myself immediately was aroused by the captivating curves of paddle -1 and its interaction with the ball, I wanted to have violent sex, but no matter how hard I tried I could not have sex with **ANY** of the characters. Please fix this immediately.

**Comment by cinderowo** [comment]
Hi, "Skoove",
As of current, the development team at cinder-OwO do not have plans on
allowing you to have sexual intercourse with paddle -1, as it is a minor.
There may be implemented a mechanic to see Ball's genitals, however that
would require removing paddle -1, a core component of the gameplay.

Please continue to watch for future updates, as we may decide to progress
with your requests.

Thanks, cinder-OwO.

**Comment by skoove** [comment]
EXCUSE ME *BUDDY* why cant I have violent sex with paddle -1, Yes they are a minor, but now I am even more aroused! Age is just a number and this is a fictional character anyway. I am disgusted at this discrimination towards me just because I want to have violent sex with paddle -1. Riddle me this code monkey, If I wanted to have sex with this dog, does that make me a zoophile? It has huge tits!
![Dog with big tits to considor](https://i.imgur.com/mVundMA.png)

Thank you for your consideration code monkey.

**Comment by cinderowo** [comment]
Please refrain from calling me something so derogatory and insulting to minorities, such as "c\*de m\*nkey"

In response to your arguments, you are actually still scum.
Here I shall list 5 reasons why you suck;
- a dog is still a dog if it has tits
- a child is still a child if *you* think it is sexy because, children really are not sex y 
- age may be just a number, but it closely ties in with human morals revolving around consent and sex, and the arbitrary number we use to define age still resembles some amount of maturity
- even if you do not agree, there are still severe consequences for sexing children and dogs in the real world, so get offline and touch some grass kiddo
- you suck, stupid

**Comment by skoove** [comment]
HAHAHA YOU CANT EVEN USE MD DUMBASS YOU ARE SO FUCKING DUMB YOU DONT KNOW HOW TO USE A \* WITHOUT IT MAKING ITALICS YOU DUMB USELESS PEICE OF SHIT

**Comment by cinderowo** [comment]
when

**Comment by cinderowo** [comment]
when did i ask

**Comment by skoove** [comment]
when what
?

**Comment by cinderowo** [comment]
when did i ask

**Comment by cinderowo** [comment]
when did i ask

**Comment by skoove** [comment]
i assed
